# Generated by Django 3.2.7 on 2021-10-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('state', models.CharField(choices=[('building', 'Building'), ('operating', 'Operating'), ('closed', 'Closed')], default='pending', max_length=255)),
                ('logo_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('logo_thumbnail_url', models.URLField(blank=True, null=True)),
                ('social', models.ManyToManyField(to='core.Social')),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
        ),
    ]
