# Generated by Django 3.2.7 on 2021-10-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='social',
            new_name='socials',
        ),
    ]
