# Generated by Django 3.2.7 on 2021-10-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_social_product_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('building', 'Building'), ('operating', 'Operating'), ('closed', 'Closed')], default='building', max_length=10),
        ),
    ]
