# Generated by Django 3.2.7 on 2021-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_type',
            field=models.CharField(choices=[('IM', 'Indie Maker'), ('DEV', 'Desarrollador'), ('MAK', 'Maker')], default='IM', max_length=10, verbose_name='Tipo de Creador'),
            preserve_default=False,
        ),
    ]
