# Generated by Django 3.2.7 on 2021-10-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211003_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creator_type',
            field=models.CharField(choices=[('IM', 'Indie Maker'), ('DEV', 'Desarrollador'), ('MAK', 'Maker')], max_length=10, verbose_name='Creator type'),
        ),
    ]
