# Generated by Django 3.2.7 on 2021-10-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_creator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='patreon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='temporal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='creator_type',
            field=models.CharField(choices=[('IM', 'Indie Maker'), ('DEV', 'Developer'), ('MAK', 'Maker')], max_length=10, verbose_name='Creator type'),
        ),
    ]
