# Generated by Django 3.2.7 on 2021-10-12 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('accounts', '0005_auto_20211007_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Is onboarding completed'),
        ),
        migrations.CreateModel(
            name='ProductRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_owner', models.BooleanField()),
                ('is_collaborator', models.BooleanField()),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_product', to='resources.resource')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='product_relation',
            field=models.ManyToManyField(through='accounts.ProductRelationship', to='resources.Resource'),
        ),
    ]
