# Generated by Django 3.2.7 on 2021-10-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211012_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrelationship',
            old_name='followed',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productrelationship',
            old_name='follower',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='productrelationship',
            name='is_collaborator',
        ),
        migrations.RemoveField(
            model_name='productrelationship',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='productrelationship',
            name='is_following',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrelationship',
            name='rights',
            field=models.CharField(choices=[('owner', 'Is owner'), ('collaborator', 'Is collaborator')], default=True, max_length=30),
            preserve_default=False,
        ),
    ]
