# Generated by Django 3.2.7 on 2021-10-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211014_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrelationship',
            name='rights',
            field=models.CharField(choices=[('owner', 'Is owner'), ('collaborator', 'Is collaborator')], max_length=30, null=True),
        ),
    ]
