# Generated by Django 3.2.7 on 2021-10-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_state'),
        ('accounts', '0009_alter_productrelationship_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrelationship',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='product_relation',
            field=models.ManyToManyField(through='accounts.ProductRelationship', to='products.Product'),
        ),
        migrations.AddConstraint(
            model_name='productrelationship',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='Anti_duplicated_relation'),
        ),
    ]
