# Generated by Django 3.2.7 on 2021-10-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_owner'),
        ('accounts', '0010_auto_20211014_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product_relation',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.DeleteModel(
            name='ProductRelationship',
        ),
    ]
