# Generated by Django 3.2.7 on 2021-10-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_monthly', models.FloatField()),
                ('price_yearly', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
