# Generated by Django 3.2.7 on 2021-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
