# Generated by Django 3.2.7 on 2021-10-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
