# Generated by Django 3.2.7 on 2021-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
