# Generated by Django 3.2.7 on 2021-10-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20211006_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['created_at'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
    ]
