# Generated by Django 3.2.7 on 2021-10-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20211006_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='categories', to='resources.Category', verbose_name='Category'),
        ),
    ]
