# Generated by Django 3.2.7 on 2021-10-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_resource_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='category',
            new_name='categories',
        ),
    ]
