# Generated by Django 3.2.7 on 2021-10-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_rename_category_resource_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
