# Generated by Django 3.2.7 on 2021-10-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_rename_category_resource_categories'),
        ('resources', '0007_resource_title'),
    ]

    operations = [
    ]
