# Generated by Django 3.2.7 on 2021-10-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20211010_2300'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('resource', 'voted_by'), name='unique_vote'),
        ),
    ]
